# Application name and authentication
spring:
  application:
    name: service-valuation
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:changeme}
  profiles:
    active:
    - 8060

# Service registry
eureka:
  client:
    # Set service registry URL
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:changeme}@${EUREKA_HOST:eureka-7900}:7900/eureka/


# Admin monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
---
spring:
  profiles: 8060
server:
  port: 8060
---
spring:
  profiles: 8061
server:
  port: 8061
