server:
  port: 6010
spring:
  application:
    name: cloud-admin
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:changeme}
  # Email settings
  mail:
    host: ${MAIL_SMTP_HOST:smtp.example.com}
    username: ${MAIL_USERNAME:user@example.com}
    password: ${MAIL_PASSWORD:changeme}
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
# Recipient email
spring.boot.admin.notify.mail.to: ${MAIL_TO:admin@example.com}
# Sender email
spring.boot.admin.notify.mail.from: ${MAIL_FROM:noreply@example.com}

# Service registry
eureka:
  client:
    # Set service registry URL
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:changeme}@${EUREKA_HOST:eureka-7900}:7900/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1

management:
  endpoints:
    web:
      exposure:
        # In YAML use double quotes; in properties files quotes are not needed
        include: "*"
  endpoint:
    health:
      # Default is never
      show-details: ALWAYS
      enabled: true
